---
# tasks file for Gitlab
- name: Update Repositories
  become: yes
  apt:
    update_cache: yes

- name: Install Prerequisites
  become: yes
  apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - apt-transport-https
      - ca-certificates
      - postfix

- name: Create gitlab automation directory
  become: yes
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - '/root/.gitlab_automate'

- name: Create script.deb.sh File
  become: yes
  copy:
    src: script.deb.sh
    dest: /root/.gitlab_automate/script.deb.sh

- name: Change permissions on script.deb.sh
  become: yes
  file:
    path: /root/.gitlab_automate/script.deb.sh
    mode: "u+rwx"
  ignore_errors: "{{ ansible_check_mode }}"

- name: Create gitlab_init.sh File
  become: yes
  copy:
    src: gitlab_init.sh
    dest: /root/.gitlab_automate/gitlab_init.sh

- name: Change permissions on gitlab_init.sh
  become: yes
  file:
    path: /root/.gitlab_automate/gitlab_init.sh
    mode: "u+rwx"
  ignore_errors: "{{ ansible_check_mode }}"

- name: Run Gitlab Initialization script
  become: yes
  command: /root/.gitlab_automate/gitlab_init.sh
  args:
    executable: /bin/bash

- name: Update Repositories
  become: yes
  apt:
    update_cache: yes

- name: Install Gitlab-CE
  become: yes
  apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - gitlab-ce
